"""init0

Revision ID: 202d122da1d6
Revises: 1fe83982ca31
Create Date: 2025-10-09 14:21:16.471047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202d122da1d6'
down_revision: Union[str, Sequence[str], None] = '1fe83982ca31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('user_id_from', sa.Integer(), nullable=False),
    sa.Column('user_id_to', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_from'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id_to'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
