"""Price history stocks

Revision ID: 2076b70eb34d
Revises: 114cc6c9424b
Create Date: 2025-10-26 19:13:50.498436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2076b70eb34d'
down_revision: Union[str, Sequence[str], None] = '114cc6c9424b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('price_history', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'price_history')
    # ### end Alembic commands ###
