"""holdings added

Revision ID: 7e8c89ce6464
Revises: 202d122da1d6
Create Date: 2025-10-09 20:00:50.937728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e8c89ce6464'
down_revision: Union[str, Sequence[str], None] = '202d122da1d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('average_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_stocks',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.drop_table('transactions')
    op.add_column('accounts', sa.Column('name', sa.Text(), nullable=False))
    op.add_column('accounts', sa.Column('email', sa.Text(), nullable=False))
    op.add_column('accounts', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('accounts', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'accounts', ['email'])
    op.drop_column('accounts', 'nome')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('nome', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'accounts', type_='unique')
    op.drop_column('accounts', 'created_at')
    op.drop_column('accounts', 'is_admin')
    op.drop_column('accounts', 'email')
    op.drop_column('accounts', 'name')
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('user_id_from', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id_to', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id_from'], ['accounts.id'], name=op.f('transactions_user_id_from_fkey')),
    sa.ForeignKeyConstraint(['user_id_to'], ['accounts.id'], name=op.f('transactions_user_id_to_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey'))
    )
    op.drop_table('account_stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
